steps:
  # 1. 构建镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/zju-website', '.']

  # 2. 推送镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/zju-website']

  # 3. 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'zju-website'
      - '--image'
      - 'gcr.io/$PROJECT_ID/zju-website'
      - '--region'
      - 'us-east1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/zju-website'

options:
  machineType: 'E2_HIGHCPU_8'
