steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/zju-website', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/zju-website']
  # 部署后需在 Cloud Run 控制台手动设置环境变量：DATABASE_URL、NEXTAUTH_SECRET、NEXTAUTH_URL、ADMIN_USERNAME、ADMIN_PASSWORD
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'zju-website', '--image', 'gcr.io/$PROJECT_ID/zju-website', '--region', 'us-east1', '--allow-unauthenticated']
