steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/zju-donation:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/zju-donation:latest'
      - '.'
    id: build

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/zju-donation:$COMMIT_SHA']
    id: push-sha
    waitFor: ['build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/zju-donation:latest']
    id: push-latest
    waitFor: ['build']

images:
  - 'gcr.io/$PROJECT_ID/zju-donation:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/zju-donation:latest'

# 增加内存，避免 Next.js 构建 OOM
options:
  machineType: 'E2_HIGHCPU_8'
